### PR TITLE
Wrong language for syntax highlighting

### LINKED ISSUE #280: [JENKINS-64584] Wrong language for syntax highlighting
<p>With the added support of translation files the current implementation of language detection isn't anymore enough, as a file extension could be used for different usage. So SourcePrinter::selectLanguageClass always decide that file extension *.ts means typescript, but it could be now also markup (as it as qt translation file). This leads to interesting coloring of the file - and tons of useless html tags</p>

<p> </p>

<p>There are different possibilities to fix this:</p>
<ul>
	<li>The IssueParser within AnalysisModel could store the language and the WNG plugin matches it to the available prism languages (e.g. xml => markup). So the language decision could be overwritten by the parser</li>
	<li>Add option in Jenkins settings to adjust the file extension mapping. This could be useful as the mapping is already incomplete (e.g. glsl is supported by Prism, but not by the plugin)</li>
	<li>Add this options not globally, but per project.</li>
	<li>Add language auto detection<br/>
 </li>
</ul>

<p>First option would be a fix without the need the user has to do sth. Second & third has the benefit that further languages could be added. </p>

<p>As we have a lot of different jobs for the same project second option would be best for us, but in case Jenkins is used for different projects (e.g. a Qt C++ project and a Typescript project) third option may be better. An combination would also be an option (e.g. create globally different named file mapping and within the call to recordIssue you reference one of the named mapping).</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=sunblack">sunblack</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64584" target="_blank">Wrong language for syntax highlighting </a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: prism-api-plugin
<li><b>label(s)</b>: help-wanted
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 20260107-220949
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>With the added support of translation files the current implementation of language detection isn't anymore enough, as a file extension could be used for different usage. So SourcePrinter::selectLanguageClass always decide that file extension *.ts means typescript, but it could be now also markup (as it as qt translation file). This leads to interesting coloring of the file - and tons of useless html tags</p>

<p> </p>

<p>There are different possibilities to fix this:</p>
<ul>
	<li>The IssueParser within AnalysisModel could store the language and the WNG plugin matches it to the available prism languages (e.g. xml =&gt; markup). So the language decision could be overwritten by the parser</li>
	<li>Add option in Jenkins settings to adjust the file extension mapping. This could be useful as the mapping is already incomplete (e.g. glsl is supported by Prism, but not by the plugin)</li>
	<li>Add this options not globally, but per project.</li>
	<li>Add language auto detection
 </li>
</ul>

<p>First option would be a fix without the need the user has to do sth. Second &amp; third has the benefit that further languages could be added. </p>

<p>As we have a lot of different jobs for the same project second option would be best for us, but in case Jenkins is used for different projects (e.g. a Qt C++ project and a Typescript project) third option may be better. An combination would also be an option (e.g. create globally different named file mapping and within the call to recordIssue you reference one of the named mapping).</p></pre>
</details>
</details>

### PR DESCRIPTION
**Pull request by akash-manna-sky**
Wrong language for syntax highlighting

Fixes #280 

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests that demonstrate the feature works or the issue is fixed

### CODE REVIEW

File: src/main/java/io/jenkins/plugins/prism/SourcePrinter.java [hunk 1]
```diff
@@ -69,7 +69,7 @@ String render(final String fileName, final Stream<String> lines, final Marker ma
             StringBuilder marked = readBlockUntilLine(stream, end);
             StringBuilder after = readBlockUntilLine(stream, Integer.MAX_VALUE);
 
-            String language = selectLanguageClass(fileName);
+            String language = selectLanguageClass(fileName, before, marked, after);
```
Comment (uhafner) [inline src/main/java/io/jenkins/plugins/prism/SourcePrinter.java]: Just look in `before`.

File: src/main/java/io/jenkins/plugins/prism/SourcePrinter.java [hunk 2]
```diff
@@ -150,8 +150,15 @@ private UnescapedText unescape(final String message) {
     }
 
     @SuppressWarnings({"javancss", "PMD.CyclomaticComplexity"})
-    private String selectLanguageClass(final String fileName) {
-        return switch (StringUtils.substringAfterLast(fileName, ".")) {
+    private String selectLanguageClass(final String fileName,
+            final StringBuilder before, final StringBuilder marked, final StringBuilder after) {
+        String extension = StringUtils.substringAfterLast(fileName, ".");
+
+        if ("ts".equals(extension) && looksLikeMarkup(before, marked, after)) {
```
Comment (uhafner) [inline src/main/java/io/jenkins/plugins/prism/SourcePrinter.java]: Simplify, no extra method is needed:

```suggestion
        if ("ts".equals(extension) && StringUtils.CS.contains(before, QT_LINGUIST_PATTERN)) {
```

And `QT_LINGUIST_PATTERN` should be defined as `"<!DOCTYPE TS>"`.

File: src/test/java/io/jenkins/plugins/prism/SourcePrinterTest.java [hunk 3]
```diff
@@ -221,6 +223,36 @@ void shouldRenderXmlFiles() {
...
+
+    @Test
+    @org.junitpioneer.jupiter.Issue("JENKINS-64584")
+    void shouldRenderQtTranslationFileAsMarkup() {
+        Marker issue = new MarkerBuilder().build();
+        SourcePrinter printer = new SourcePrinter();
+
+        Document document = Jsoup.parse(printer.render("sample.ts", Stream.of(
+                "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
+                "<TS version=\"2.1\"><context><name>MainWindow</name></context></TS>"), issue));
```
Comment (uhafner) [inline src/test/java/io/jenkins/plugins/prism/SourcePrinterTest.java]: Where did you get the example from? All my search results look like:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
  <context>
    <name>MainWindow</name>
    <message>
      <source>Hello, world!</source>
      <translation>Hello, world!</translation>
    </message>
    <message>
      <source>File not found</source>
      <translation>File not found</translation>
    </message>
  </context>
</TS>
```

**Review by uhafner — CHANGES_REQUESTED** [review]

**Review by uhafner — APPROVED** [review]
Thanks!

**Comment by akash-manna-sky** [comment]
Thanks!
